#!/usr/bin/python3

import os
import subprocess
import shutil

script_base_dir = os.getcwd()
cmd = 'rtiddsgen'
platform = 'x64Linux4gcc7.3.0'
platform_arg = " -platform " + platform
language = "C++"
language_arg = " -language " + language
update_arg = " -autoGenFiles " + platform
constructor_arg = " -constructor"
enumarg = " -qualifiedEnumerator "

final_command = cmd + platform_arg + language_arg + update_arg + constructor_arg + enumarg
print(final_command)

subprocess.call(['mkdir', 'AUTOGENERATED'])
autogen_dir = script_base_dir + os.path.sep + 'AUTOGENERATED'
print(autogen_dir)

generated_types = []
for root,dirs,files in os.walk(script_base_dir):
    for file in files:
        if file.endswith('.idl'):
            #print(os.path.join(root,file))
            generated_type_dirname = '' + os.path.splitext(file)[0]
            #print(generated_type_dirname)
            os.chdir(autogen_dir)
            subprocess.call(['mkdir', generated_type_dirname])
            generated_type_dir = os.getcwd() + os.path.sep + generated_type_dirname
            os.chdir(generated_type_dir)


            #print(os.path.join(root,file))
            cmd = final_command + ' -inputIDL ' + os.path.join(root,file) + ' -d ' + os.getcwd()
            os.system(cmd)
            make_cmd = 'make -f ' + 'makefile_' + generated_type_dirname + '_' + platform
            os.system(make_cmd)

            generated_types.append(generated_type_dirname)

# Report to a file which types were generated
os.chdir(script_base_dir)
with open('generated_types.txt', 'w') as f:
    for item in generated_types:
        f.write("%s\n" % item)

subprocess.call(['mkdir', 'M12Typelib'])
os.chdir(script_base_dir + os.path.sep + 'M12Typelib')
subprocess.call(['mkdir', 'include'])
subprocess.call(['mkdir', 'objs'])

os.chdir(script_base_dir)
for dirpath, dirnames, filenames in os.walk('.'):
    for filename in [f for f in filenames if f.endswith(".o")]:
        print(os.path.join(dirpath,filename))
        shutil.copyfile(os.path.join(dirpath,filename), os.getcwd() + os.path.sep + 'M12Typelib' + os.path.sep + 'objs' + os.path.sep + filename )
    for filename in [f for f in filenames if f.endswith(".h")]:
        print(os.path.join(dirpath,filename))
        shutil.copyfile(os.path.join(dirpath,filename), os.getcwd() + os.path.sep + 'M12Typelib' + os.path.sep + 'include' + os.path.sep + filename )
            #subprocess.call(['touch', generated_type_dirname + '.txt'])
            #subprocess.call(['mkdir', dirname])
#cmd_args = '-language C++ -platform ' + platform + 'inputIDL'
#op = subprocess.check_output(['echo', platform])
#print(op)
#asd = os.system("mkdir ")
