enum hsd_direction_enum{FORWARD, BACKWARD, UNKNOWN};

struct M12_input_and_hsd{
uint8 gas_pedal;
boolean buttons[4];
int8 joystick_x;
int8 joystick_y;
uint16 hsd_motor_speed;
hsd_direction_enum hsd_direction;
};
