enum liftIO_enum{EXTENDING, RETRACTING};
enum liftdiff_enum{EXTENDING, RETRACTING};
enum tiltIO_enum{EXTENDING, RETRACTING};
enum tiltdiff_enum{EXTENDING, RETRACTING};
enum gear_enum{TURTLE, RABBIT};

struct WorkHydraulicsRequests{
	uint8 power_request_;
	uint16 rotational_speed_request;
	uint8 calculated_power;
	uint8 calculated_power_reference_system;
	uint8 auxiliary_pump_pressure;
	liftIO_enum liftIO;
	liftdiff_enum liftdiff;
	tiltIO_enum tiltIO;
	tiltdiff_enum tiltdiff;
};